web:
  build: .
  working_dir: /Flask_Docker
  command: python main.py
  links:
    - db
  volumes:
    - .:/data
  ports:
    - "5005:5005"

db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: gabriela123
  ports:
    - "3309:3309"